name: PitRedux
version: '${project.version}'
main: me.keegan.pitredux.ThePitRedux
api-version: '1.16'
softdepend: [NoteBlockAPI, Citizens]
commands:
  hello:
    description: test
    usage: /<command>
  announce:
    description: Announce any message to all players
    usage: /<command> message